//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatternMaker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PatternEntities : DbContext
    {
        public PatternEntities()
            : base("name=PatternEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ControllerName> ControllerNames { get; set; }
        public DbSet<ControllerUser> ControllerUsers { get; set; }
        public DbSet<StateTransition> StateTransitions { get; set; }
    }
}
