//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatternMaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateTransition
    {
        public int Id { get; set; }
        public string StateName { get; set; }
        public string MethodName { get; set; }
        public string MethodParameter { get; set; }
        public string Description { get; set; }
        public string NextState { get; set; }
        public int ControllerID { get; set; }
    
        public virtual ControllerName ControllerName { get; set; }
    }
}
